# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'HEI-GIS-TSYSTEMSAD-O365AzureAD (d84cc03f-38bb-41db-85ec-976fba7dc462)'
    subscriptionId: 'd84cc03f-38bb-41db-85ec-976fba7dc462'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'HEI-EUD-PowerBI-P-AZWE-RG-01'
    location: 'West US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/ssenthilec09/Repository_Public_100/blob/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName myarmpipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

